steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/project-isolution/isolution-artifact-repo/isolution-app:${SHORT_SHA}', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-isolution/isolution-artifact-repo/isolution-app:${SHORT_SHA}']

# Store images in Google Artifact Registry
images:
  - us-central1-docker.pkg.dev/project-isolution/isolution-artifact-repo/isolution-app/my-app:${SHORT_SHA}
